import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const errors = [];
const forbiddenTerms = [
  ".cla" + "ude",
  ".r" + "oo",
  "/" + "zoo-",
  "ask-" + "matt",
  "Ask" + "UserQuestion",
  "Todo" + "Write",
  "`" + "Ag" + "ent` tool",
];
const requiredFiles = ["skills", "commands", "rules", "scripts", "compat", "extensions", "README.md", "CHANGELOG.md", "LICENSE"];

function report(path, message) {
  errors.push(`${relative(root, path) || "."}: ${message}`);
}

function filesIn(directory) {
  if (!existsSync(directory)) return [];
  const entries = readdirSync(directory, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const path = resolve(directory, entry.name);
    return entry.isDirectory() ? filesIn(path) : entry.isFile() ? [path] : [];
  });
}

function readText(path) {
  try {
    return readFileSync(path, "utf8");
  } catch (error) {
    report(path, `cannot read file (${error.message})`);
    return "";
  }
}

function frontmatter(path) {
  const text = readText(path);
  const match = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(text);
  if (!match) {
    report(path, "missing YAML frontmatter delimited by ---");
    return null;
  }

  const fields = new Map();
  const lines = match[1].split(/\r?\n/);
  for (let index = 0; index < lines.length; index += 1) {
    const field = /^([A-Za-z][\w-]*):(?:\s*(.*))?$/.exec(lines[index]);
    if (!field) continue;
    let value = field[2].trim();
    if (value === ">" || value === "|") {
      const block = [];
      while (/^\s+/.test(lines[index + 1] ?? "")) block.push(lines[++index].trim());
      value = value === ">" ? block.join(" ") : block.join("\n");
    }
    fields.set(field[1], value.replace(/^(["'])(.*)\1$/, "$2"));
  }
  return { raw: match[0], fields };
}

function validSkillName(value) {
  return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value);
}

function runBuildPiCompatCheck() {
  try {
    execSync("node scripts/build-pi-compat.js --check", { cwd: root, stdio: "ignore" });
  } catch (error) {
    report(root, "build:pi-compat --check failed; generated compat files are stale or missing");
  }
}

function checkPiManifest() {
  const path = resolve(root, "package.json");
  if (!existsSync(path)) return;

  let manifest;
  try {
    manifest = JSON.parse(readText(path));
  } catch (error) {
    report(path, `invalid JSON (${error.message})`);
    return;
  }

  if (!manifest.pi || typeof manifest.pi !== "object") {
    report(path, "pi manifest must be an object with skills and prompts");
    return;
  }

  const expectedSkills = ["./compat/pi/skills"];
  const expectedPrompts = ["./compat/pi/prompts"];

  if (!Array.isArray(manifest.pi.skills) || JSON.stringify(manifest.pi.skills) !== JSON.stringify(expectedSkills)) {
    report(path, `pi.skills must be exactly ["./compat/pi/skills"]`);
  }
  if (!Array.isArray(manifest.pi.prompts) || JSON.stringify(manifest.pi.prompts) !== JSON.stringify(expectedPrompts)) {
    report(path, `pi.prompts must be exactly ["./compat/pi/prompts"]`);
  }
  for (const key of Object.keys(manifest.pi)) {
    if (key !== "skills" && key !== "prompts") report(path, `pi must not configure ${key}`);
  }
}

function checkCompatFiles() {
  const compatDir = resolve(root, "compat/pi");
  const skillsDir = resolve(compatDir, "skills");
  const promptsDir = resolve(compatDir, "prompts");

  if (!existsSync(compatDir)) {
    report(compatDir, "compat/pi directory is missing (should be generated by build:pi-compat)");
    return;
  }
  if (!existsSync(skillsDir)) {
    report(skillsDir, "compat/pi/skills directory is missing");
    return;
  }
  if (!existsSync(promptsDir)) {
    report(promptsDir, "compat/pi/prompts directory is missing");
    return;
  }

  const skills = new Set();
  for (const entry of readdirSync(resolve(root, "skills"), { withFileTypes: true })) {
    if (entry.isDirectory()) skills.add(entry.name);
  }
  const expectedPrompts = new Set();
  for (const path of filesIn(resolve(root, "commands"))) {
    const name = path.slice(0, -3).split("/").pop().split("\\").pop();
    expectedPrompts.add(name);
  }

  for (const entry of readdirSync(skillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const skillDir = resolve(skillsDir, entry.name);
    const skillFile = resolve(skillDir, "SKILL.md");
    if (!existsSync(skillFile)) {
      report(skillDir, "compat skill directory missing SKILL.md");
      continue;
    }
    if (!skills.has(entry.name)) {
      report(skillFile, `compat skill ${entry.name} has no canonical skill`);
    }
    const text = readText(skillFile);
    if (!text.includes("Canonical skill: `../../../../skills/")) {
      report(skillFile, "compat skill missing canonical skill reference");
    }
    if (!text.includes("Original Pi Translation Contract")) {
      report(skillFile, "compat skill missing translation contract");
    }
  }

  for (const skill of skills) {
    const skillDir = resolve(skillsDir, skill);
    const skillFile = resolve(skillDir, "SKILL.md");
    if (!existsSync(skillFile)) {
      report(skillFile, `missing generated compat skill ${skill}`);
    }
  }

  for (const prompt of expectedPrompts) {
    const promptFile = resolve(promptsDir, `${prompt}.md`);
    if (!existsSync(promptFile)) {
      report(promptFile, `missing generated compat prompt ${prompt}`);
    } else {
      const text = readText(promptFile);
      if (!text.includes("$ARGUMENTS")) {
        report(promptFile, "compat prompt missing $ARGUMENTS placeholder");
      }
    }
  }

  for (const entry of readdirSync(promptsDir, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
    const name = entry.name.slice(0, -3);
    if (!expectedPrompts.has(name)) {
      report(resolve(promptsDir, entry.name), `extra generated compat prompt ${name}`);
    }
  }
}

function checkManifest() {
  const path = resolve(root, "package.json");
  if (!existsSync(path)) {
    report(path, "missing package manifest");
    return;
  }

  let manifest;
  try {
    manifest = JSON.parse(readText(path));
  } catch (error) {
    report(path, `invalid JSON (${error.message})`);
    return;
  }

  if (manifest.name !== "@fernado03/pi-flow") report(path, "name must be @fernado03/pi-flow");
  if (manifest.version !== "0.2.7") report(path, "version must be 0.2.7");
  if (manifest.type !== "module") report(path, "type must be module");
  for (const field of ["dependencies", "devDependencies", "optionalDependencies", "peerDependencies", "bundledDependencies"]) {
    const value = manifest[field];
    if (Array.isArray(value) ? value.length : Object.keys(value ?? {}).length) {
      report(path, `${field} must be absent or empty for a dependency-free package`);
    }
  }
  if (!manifest.omp || typeof manifest.omp.name !== "string" || !manifest.omp.name.trim() ||
      typeof manifest.omp.description !== "string" || !manifest.omp.description.trim()) {
    report(path, "omp must provide non-empty name and description");
  } else {
    for (const key of Object.keys(manifest.omp)) {
      if (key !== "name" && key !== "description" && key !== "extensions") report(path, `omp must not configure runtime integration ${key}`);
    }
    const extensions = manifest.omp.extensions;
    if (!Array.isArray(extensions) || extensions.length !== 1 || extensions[0] !== "./extensions/index.ts") {
      report(path, "omp.extensions must be exactly [\"./extensions/index.ts\"]");
    }
  }
  for (const field of ["main", "module", "exports", "bin"]) {
    if (field in manifest) report(path, `must not define runtime entry ${field}`);
  }
  if (!Array.isArray(manifest.files) || manifest.files.length !== requiredFiles.length ||
      requiredFiles.some((file) => !manifest.files.includes(file)) ||
      manifest.files.some((file) => !requiredFiles.includes(file))) {
    report(path, `files must list exactly: ${requiredFiles.join(", ")}`);
  }
  if (manifest.scripts?.check !== "node scripts/check.js") report(path, "scripts.check must run node scripts/check.js");
  if (manifest.scripts?.["pack:check"] !== "npm pack --dry-run") report(path, "scripts.pack:check must run npm pack --dry-run");
  for (const file of requiredFiles) {
    const artifact = resolve(root, file);
    if (!existsSync(artifact)) report(artifact, "required published artifact is missing");
  }
}

function checkSkills() {
  const directory = resolve(root, "skills");
  if (!existsSync(directory)) return new Set();

  const skills = new Set();
  let visibleMetadata = 0;
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = resolve(directory, entry.name);
    if (!entry.isDirectory()) {
      report(path, "nested skill layout requires skills/<name>/SKILL.md, not a file directly in skills");
      continue;
    }

    const skillFile = resolve(path, "SKILL.md");
    if (!existsSync(skillFile)) {
      report(path, "nested skill layout requires SKILL.md directly inside this skill directory");
      continue;
    }
    for (const nestedSkill of filesIn(path).filter((file) => file.endsWith("SKILL.md") && file !== skillFile)) {
      report(nestedSkill, "nested skill layout is not supported; move the skill to skills/<name>/SKILL.md");
    }

    const metadata = frontmatter(skillFile);
    if (!metadata) continue;
    const name = metadata.fields.get("name");
    const description = metadata.fields.get("description");
    if (!name || !validSkillName(name)) report(skillFile, "frontmatter name must be a lowercase hyphenated identifier");
    if (!description) report(skillFile, "frontmatter description must be non-empty");
    else if (description.length > 180) report(skillFile, "frontmatter description exceeds 180 characters");
    if (name) {
      if (skills.has(name)) report(skillFile, `duplicate skill name ${name}`);
      skills.add(name);
    }
    if (metadata.fields.get("disable-model-invocation") !== "true") visibleMetadata += metadata.raw.length;
  }

  if (visibleMetadata > 8000) {
    report(directory, `visible skill metadata is ${visibleMetadata} characters; limit is 8000`);
  }
  return skills;
}

function checkCommands(skills) {
  const directory = resolve(root, "commands");
  if (!existsSync(directory)) return;

  for (const path of filesIn(directory)) {
    const bytes = statSync(path).size;
    if (bytes > 1000) report(path, `command wrapper is ${bytes} bytes; limit is 1000`);
    const text = readText(path);
    const references = [...text.matchAll(/skill:\/\/([^\s`]+)/g)];
    if (references.length !== 1) {
      report(path, `command wrapper must contain exactly one skill:// reference; found ${references.length}`);
      continue;
    }
    const skill = /^(?<name>[a-z0-9]+(?:-[a-z0-9]+)*)(?:\/SKILL\.md)?$/.exec(references[0][1])?.groups?.name;
    if (!skill) {
      report(path, `invalid skill reference skill://${references[0][1]}`);
      continue;
    }
    if (!skills.has(skill)) report(path, `references nonexistent skill ${skill}`);
  }
}

function checkRules() {
  const directory = resolve(root, "rules");
  if (!existsSync(directory)) return;
  const bytes = filesIn(directory).reduce((total, path) => total + statSync(path).size, 0);
  if (bytes > 1200) report(directory, `always-loaded rules total ${bytes} bytes; limit is 1200`);
}

function checkForbiddenTerms() {
  for (const path of filesIn(root)) {
    if (relative(root, path).split(sep).includes("node_modules")) continue;
    const text = readText(path);
    for (const term of forbiddenTerms) {
      if (text.includes(term)) report(path, `contains unsupported platform marker ${term}`);
    }
  }
}

function checkOutputPaths() {
  const obsoletePaths = [".scratch/", ".out-of-scope/", ".pi-flow/scratch/"];
  const published = ["skills", "commands", "rules", "compat", "README.md", "CHANGELOG.md"];
  for (const entry of published) {
    const resolved = resolve(root, entry);
    const files = existsSync(resolved) && statSync(resolved).isFile() ? [resolved] : filesIn(resolved);
    for (const path of files) {
      const relativePath = relative(root, path).split(sep).join("/");
      if (relativePath === "CHANGELOG.md") continue;
      const text = readText(path);
      for (const pattern of obsoletePaths) {
        if (text.includes(pattern)) {
          report(path, `contains obsolete path ${pattern}; write output under .pi-flow/ instead`);
        }
      }
    }
  }
}

runBuildPiCompatCheck();
checkManifest();
checkPiManifest();
const skills = checkSkills();
checkCommands(skills);
checkRules();
checkForbiddenTerms();
checkOutputPaths();
checkCompatFiles();

if (errors.length) {
  console.error(`Pi Flow package check failed with ${errors.length} violation${errors.length === 1 ? "" : "s"}:`);
  for (const error of errors) console.error(`- ${error}`);
  process.exitCode = 1;
} else {
  console.log("Pi Flow package check passed.");
}